#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "PyYAML>=6.0",
# ]
# ///
"""
Generic Values Renderer

This script renders configuration values by:
1. Reading config.yaml to get the list of shards and their configurations
2. For each shard and cluster type, loading defaults from existing values files
3. Merging shard-specific overrides with defaults
4. Outputting merged values files to rendered/{environment}/{sector}/{region}/{clustertype}-values.yaml

The script is completely transparent and does no magic - it simply merges YAML values.
"""

import sys
from pathlib import Path
from typing import Any, Dict, List

import yaml


def load_yaml(file_path: Path) -> Dict[str, Any]:
    """Load and parse a YAML file.

    Args:
        file_path: Path to the YAML file

    Returns:
        Parsed YAML content as a dictionary
    """
    if not file_path.exists():
        return {}

    with open(file_path, 'r') as f:
        return yaml.safe_load(f) or {}


def save_yaml(data: Dict[str, Any], file_path: Path, cluster_type: str, shard: Dict[str, Any]) -> None:
    """Save a dictionary as a YAML file with proper headers.

    Args:
        data: Dictionary to save
        file_path: Path where to save the YAML file
        cluster_type: Type of cluster (managementcluster, regionalcluster, etc.)
        shard: Shard configuration
    """
    file_path.parent.mkdir(parents=True, exist_ok=True)

    # Generate header
    region = shard['region']
    environment = shard['environment']
    sector = shard['sector']

    header = f"""# GENERATED FILE - DO NOT EDIT MANUALLY
#
# This file is automatically generated by the render script.
# To make changes:
# - For default changes: Edit values.yaml files in argocd/config/{cluster_type}cluster/*/values.yaml or argocd/config/shared/*/values.yaml
# - For shard-specific changes: Edit argocd/config.yaml
# - Then run: argocd/scripts/render.py
#
# Cluster Type: {cluster_type}
# Shard: {region} ({environment}/{sector})
# Generated: {Path(__file__).name}
#

"""

    with open(file_path, 'w') as f:
        f.write(header)
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True, width=float('inf'))


def deep_merge(base: Dict[str, Any], overlay: Dict[str, Any]) -> Dict[str, Any]:
    """Recursively merge two dictionaries.

    Args:
        base: Base dictionary
        overlay: Dictionary to merge into base

    Returns:
        Merged dictionary
    """
    result = base.copy()

    for key, value in overlay.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = deep_merge(result[key], value)
        else:
            result[key] = value

    return result


def get_cluster_types(base_dir: Path) -> List[str]:
    """Discover cluster types by looking at directories.

    Args:
        base_dir: Base directory to scan

    Returns:
        List of cluster type names
    """
    cluster_types = []
    for item in base_dir.iterdir():
        if item.is_dir() and not item.name.startswith('.') and item.name not in ['shared']:
            cluster_types.append(item.name)
    return cluster_types


def render_shard_values(
    shard: Dict[str, Any],
    cluster_types: List[str],
    base_dir: Path,
    rendered_dir: Path
) -> None:
    """Render values files for all cluster types for a shard.

    Args:
        shard: Shard configuration
        cluster_types: List of cluster types to render
        base_dir: Base directory containing cluster type directories
        rendered_dir: Path to the rendered output directory
    """
    environment = shard['environment']
    sector = shard['sector']
    region = shard['region']

    print(f"Processing shard: {region} ({environment}/{sector})")

    # Create output directory
    output_dir = rendered_dir / environment / sector / region
    output_dir.mkdir(parents=True, exist_ok=True)

    # Process each cluster type
    for cluster_type in cluster_types:
        # Get shard-specific values for this cluster type
        shard_cluster_values = shard.get('values', {}).get(cluster_type, {})

        # Get top-level values from the shard (not cluster-specific)
        shard_top_level_values = {k: v for k, v in shard.get('values', {}).items()
                                 if k not in cluster_types and k != 'global'}

        # Get global values that apply to this cluster type
        global_values = shard.get('values', {}).get('global', {})

        # Merge only the overrides: global_values <- shard_top_level <- shard_cluster_values
        # Do NOT include helm chart defaults - those stay in the charts
        override_values = deep_merge(global_values.copy(), shard_top_level_values)
        override_values = deep_merge(override_values, shard_cluster_values)

        # Only save if there are actual overrides
        if override_values:
            output_file = output_dir / f'{cluster_type}-values.yaml'
            save_yaml(override_values, output_file, cluster_type, shard)
            print(f"  [OK] {output_file.relative_to(rendered_dir.parent)}")
        else:
            print(f"  [SKIP] No overrides for {cluster_type}")


def main() -> int:
    """Main entry point for the script.

    Returns:
        Exit code (0 for success, 1 for error)
    """
    # Determine script location and project root
    script_dir = Path(__file__).parent
    project_root = script_dir.parent.parent

    config_file = project_root / 'argocd' / 'config.yaml'
    base_dir = project_root / 'argocd' / 'config'
    rendered_dir = project_root / 'argocd' / 'rendered'

    if not config_file.exists():
        print(f"Error: Config file not found: {config_file}", file=sys.stderr)
        return 1

    # Load config
    config = load_yaml(config_file)

    # Get shards from config
    shards = config.get('shards', [])
    if not shards:
        print("Error: No shards found in config.yaml", file=sys.stderr)
        return 1

    # Discover cluster types
    cluster_types = get_cluster_types(base_dir)
    if not cluster_types:
        print("Error: No cluster types found", file=sys.stderr)
        return 1

    print(f"Found {len(shards)} shard(s)")
    print(f"Found cluster types: {', '.join(cluster_types)}")
    print()

    # Process each shard
    for shard in shards:
        environment = shard.get('environment')
        sector = shard.get('sector')
        region = shard.get('region')

        if not (environment and sector and region):
            print(f"Warning: Skipping incomplete shard: {shard}", file=sys.stderr)
            continue

        render_shard_values(shard, cluster_types, base_dir, rendered_dir)
        print()

    print("[OK] Rendering complete")
    return 0


if __name__ == '__main__':
    sys.exit(main())