apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-management
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: "9.3.4"
    helm:
      releaseName: argocd
      values: |
        # Maintain compatibility with existing bootstrap configuration
        server:
          service:
            type: ClusterIP
          # Keep insecure mode for internal cluster access
          extraArgs:
            - --insecure

        # Preserve existing configurations from bootstrap
        configs:
          params:
            server.insecure: true

        # Resource management optimized for management clusters
        controller:
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi

        server:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

        repoServer:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi

        # High availability configuration for management cluster
        controller:
          replicas: 1  # Single replica for cost optimization

        server:
          replicas: 2  # HA for server component

        repoServer:
          replicas: 2  # HA for repo server

        # Security hardening
        global:
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            fsGroup: 999

        # Monitoring configuration
        controller:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: false # TODO(Claudio): Enable once Prometheus operator is deployed

        server:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: false

        repoServer:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: false

        # Required to not have redis re-initialized post the initial install
        # This is required to have argocd manage itself
        redis:
          secretInit:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: false    # Prevent accidental deletion of ArgoCD itself
      selfHeal: true  # Auto-fix configuration drift
    syncOptions:
      - CreateNamespace=false  # Namespace already exists from bootstrap
      - Replace=true          # Allow replacement for upgrades
      - ServerSideApply=true  # Use server-side apply for better conflict resolution
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore status differences to prevent sync loops
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status