# ArgoCD Self-Management
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-management
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.3.4
    helm:
      valuesObject:
        ha:
          enabled: true
        configs:
          params:
            server.insecure: false
        server:
          autoscaling:
            enabled: true
            minReplicas: 2
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi # Lowered to be more efficient
        controller:
          resources:
            limits:
              cpu: 1000m      # Increased to handle sync spikes
              memory: 2Gi     # Increased to prevent OOMKilled crashes
            requests:
              cpu: 500m
              memory: 1Gi     # Guaranteed 1Gi for the cache

        repoServer:
          autoscaling:
            enabled: true
            minReplicas: 2

        redisSecretInit:
          enabled: false # Ref: https://github.com/argoproj/argo-helm/issues/2887

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true      # Cleans up old resources automatically
      selfHeal: true   # Overwrites manual cluster changes
      allowEmpty: false # SAFETY: Prevents deletion if Git repo is wiped
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  ignoreDifferences:
    # Ignore Argo CD tracking annotations globally to prevent sync-loops
    - group: "*"
      kind: "*"
      managedFieldsManagers:
        - argocd-controller
      jsonPointers:
        - /metadata/annotations/argocd.argoproj.io~1tracking-id

    # Ignore Helm dynamic checksums that cause "noise" in diffs
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /metadata/annotations/checksum~1cmd-params
        - /metadata/annotations/checksum~1config
        - /metadata/annotations/checksum~1secret
    - group: ""
      kind: Secret
      jsonPointers:
        - /metadata/annotations/checksum~1cmd-params
        - /metadata/annotations/checksum~1config
        - /metadata/annotations/checksum~1secret
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/checksum~1cmd-params
        - /metadata/annotations/checksum~1config
        - /metadata/annotations/checksum~1secret
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/checksum~1cmd-params
        - /metadata/annotations/checksum~1config
        - /metadata/annotations/checksum~1secret
